from alembic import op
import sqlalchemy as sa
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('users',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('username',sa.String(100),nullable=False),sa.Column('email',sa.String(255),nullable=False),sa.Column('password_hash',sa.String(255),nullable=False),sa.Column('role',sa.Enum('ADMIN','OPERATOR','VIEWER',name='userrole'),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint('username'),sa.UniqueConstraint('email'))
    op.create_index('ix_users_username','users',['username']); op.create_index('ix_users_email','users',['email']); op.create_index('ix_users_role','users',['role'])
    op.create_table('devices',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='CASCADE'),nullable=False),sa.Column('device_identifier',sa.String(150),nullable=False),sa.Column('name',sa.String(150),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint('device_identifier')); op.create_index('ix_devices_user_id','devices',['user_id']); op.create_index('ix_devices_device_identifier','devices',['device_identifier']); op.create_index('ix_devices_is_active','devices',['is_active'])
    op.create_table('geofences',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('name',sa.String(150),nullable=False),sa.Column('description',sa.String(500)),sa.Column('geofence_type',sa.Enum('CIRCLE','POLYGON',name='geofencetype'),nullable=False),sa.Column('center_latitude',sa.Numeric(10,7)),sa.Column('center_longitude',sa.Numeric(10,7)),sa.Column('radius_meters',sa.Numeric(12,2)),sa.Column('boundary_tolerance_meters',sa.Numeric(10,2),nullable=False,server_default='10'),sa.Column('event_rules',sa.JSON(),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column('created_by',sa.Integer()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)); op.create_index('ix_geofences_name','geofences',['name']); op.create_index('ix_geofences_geofence_type','geofences',['geofence_type']); op.create_index('ix_geofences_is_active','geofences',['is_active']); op.create_index('ix_geofences_created_by','geofences',['created_by'])
    op.create_table('geofence_points',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('geofence_id',sa.Integer(),sa.ForeignKey('geofences.id',ondelete='CASCADE'),nullable=False),sa.Column('sequence',sa.Integer(),nullable=False),sa.Column('latitude',sa.Numeric(10,7),nullable=False),sa.Column('longitude',sa.Numeric(10,7),nullable=False),sa.UniqueConstraint('geofence_id','sequence',name='uq_geofence_point_sequence')); op.create_index('ix_geofence_points_geofence_id','geofence_points',['geofence_id'])
    op.create_table('location_events',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('device_id',sa.Integer(),sa.ForeignKey('devices.id',ondelete='CASCADE'),nullable=False),sa.Column('latitude',sa.Numeric(10,7),nullable=False),sa.Column('longitude',sa.Numeric(10,7),nullable=False),sa.Column('recorded_at',sa.DateTime(timezone=True),nullable=False),sa.Column('received_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint('device_id','recorded_at','latitude','longitude',name='uq_location_duplicate')); op.create_index('ix_location_events_device_id','location_events',['device_id']); op.create_index('ix_location_events_recorded_at','location_events',['recorded_at']); op.create_index('ix_location_events_device_recorded','location_events',['device_id','recorded_at'])
    op.create_table('device_geofence_states',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('device_id',sa.Integer(),sa.ForeignKey('devices.id',ondelete='CASCADE'),nullable=False),sa.Column('geofence_id',sa.Integer(),sa.ForeignKey('geofences.id',ondelete='CASCADE'),nullable=False),sa.Column('current_state',sa.Enum('INSIDE','OUTSIDE',name='geofencestate'),nullable=False),sa.Column('last_latitude',sa.Numeric(10,7),nullable=False),sa.Column('last_longitude',sa.Numeric(10,7),nullable=False),sa.Column('last_recorded_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint('device_id','geofence_id',name='uq_device_geofence_state')); op.create_index('ix_device_geofence_states_device_id','device_geofence_states',['device_id']); op.create_index('ix_device_geofence_states_geofence_id','device_geofence_states',['geofence_id'])
    op.create_table('geofence_events',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('device_id',sa.Integer(),sa.ForeignKey('devices.id',ondelete='CASCADE'),nullable=False),sa.Column('geofence_id',sa.Integer(),sa.ForeignKey('geofences.id',ondelete='CASCADE'),nullable=False),sa.Column('location_event_id',sa.Integer(),sa.ForeignKey('location_events.id',ondelete='CASCADE'),nullable=False),sa.Column('event_type',sa.Enum('ENTER','EXIT','INSIDE','OUTSIDE',name='geofenceeventtype'),nullable=False),sa.Column('previous_state',sa.Enum('INSIDE','OUTSIDE',name='geofencestate',create_type=False),nullable=False),sa.Column('current_state',sa.Enum('INSIDE','OUTSIDE',name='geofencestate',create_type=False),nullable=False),sa.Column('occurred_at',sa.DateTime(timezone=True),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint('location_event_id','geofence_id','event_type',name='uq_geofence_event_transition')); op.create_index('ix_geofence_events_device_id','geofence_events',['device_id']); op.create_index('ix_geofence_events_geofence_id','geofence_events',['geofence_id']); op.create_index('ix_geofence_events_event_type','geofence_events',['event_type']); op.create_index('ix_geofence_events_lookup','geofence_events',['device_id','geofence_id','occurred_at'])
    op.create_table('audit_logs',sa.Column('id',sa.Integer(),primary_key=True),sa.Column('user_id',sa.Integer(),sa.ForeignKey('users.id',ondelete='SET NULL')),sa.Column('action',sa.String(100),nullable=False),sa.Column('entity_type',sa.String(100),nullable=False),sa.Column('entity_id',sa.String(100)),sa.Column('details',sa.JSON()),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)); op.create_index('ix_audit_logs_user_id','audit_logs',['user_id']); op.create_index('ix_audit_logs_action','audit_logs',['action']); op.create_index('ix_audit_logs_created_at','audit_logs',['created_at'])
def downgrade():
    op.drop_table('audit_logs'); op.drop_table('geofence_events'); op.drop_table('device_geofence_states'); op.drop_table('location_events'); op.drop_table('geofence_points'); op.drop_table('geofences'); op.drop_table('devices'); op.drop_table('users')
