import { useEffect, useState } from 'react'
import { Alert, Button, Card, CardContent, Grid, Stack, Typography } from '@mui/material'
import FenceRoundedIcon from '@mui/icons-material/FenceRounded'
import DevicesOtherRoundedIcon from '@mui/icons-material/DevicesOtherRounded'
import EventAvailableRoundedIcon from '@mui/icons-material/EventAvailableRounded'
import LocationOnRoundedIcon from '@mui/icons-material/LocationOnRounded'
import RefreshRoundedIcon from '@mui/icons-material/RefreshRounded'
import { devicesApi } from '../api/devices'; import { geofencesApi } from '../api/geofences'; import { locationsApi } from '../api/locations'; import { apiError } from '../api/client'
import type { Device, Geofence, EventHistoryItem, LocationEvent } from '../types/api'
import StatCard from '../components/StatCard'; import PageHeader from '../components/PageHeader'; import Loading from '../components/Loading'; import EmptyState from '../components/EmptyState'

export default function DashboardPage() {
 const [devices,setDevices]=useState<Device[]>([]),[geofences,setGeofences]=useState<Geofence[]>([]),[events,setEvents]=useState<EventHistoryItem[]>([]),[locations,setLocations]=useState<LocationEvent[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const [d,g,e,l]=await Promise.all([devicesApi.list(),geofencesApi.list(),locationsApi.events({limit:10}),locationsApi.current()]);setDevices(d);setGeofences(g);setEvents(e);setLocations(l)}catch(err){setError(apiError(err))}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 if(loading)return <Loading text="Loading live backend data..."/>
 return <><PageHeader title="Good to see you" subtitle="A live operational snapshot from your geofencing backend." action={<Button startIcon={<RefreshRoundedIcon/>} onClick={load}>Refresh</Button>}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Grid container spacing={2.2} sx={{mb:2.5}}><Grid size={{xs:12,sm:6,lg:3}}><StatCard label="Active geofences" value={geofences.filter(g=>g.is_active).length} icon={<FenceRoundedIcon/>} tone="#f4ebf7"/></Grid><Grid size={{xs:12,sm:6,lg:3}}><StatCard label="Active devices" value={devices.filter(d=>d.is_active).length} icon={<DevicesOtherRoundedIcon/>} tone="#eaf3f8"/></Grid><Grid size={{xs:12,sm:6,lg:3}}><StatCard label="Recent events" value={events.length} icon={<EventAvailableRoundedIcon/>} tone="#f8f0e4"/></Grid><Grid size={{xs:12,sm:6,lg:3}}><StatCard label="Live locations" value={locations.length} icon={<LocationOnRoundedIcon/>} tone="#eef5ea"/></Grid></Grid><Grid container spacing={2.2}><Grid size={{xs:12,lg:7}}><Card><CardContent><Typography variant="h6" fontWeight={800} sx={{mb:2}}>Recent geofence events</Typography>{events.length===0?<EmptyState text="No geofence events recorded yet."/>:<Stack spacing={1}>{events.slice(0,6).map(e=><Stack key={e.id} direction="row" justifyContent="space-between" alignItems="center" sx={{p:1.4,borderRadius:2.5,background:'#faf8fc'}}><Stack><Typography fontWeight={700} sx={{textTransform:'capitalize'}}>{e.event_type} · Geofence #{e.geofence_id}</Typography><Typography variant="caption" color="text.secondary">Device #{e.device_id} · {new Date(e.occurred_at).toLocaleString()}</Typography></Stack><Typography variant="caption" sx={{textTransform:'uppercase'}}>{e.previous_state} → {e.current_state}</Typography></Stack>)}</Stack>}</CardContent></Card></Grid><Grid size={{xs:12,lg:5}}><Card><CardContent><Typography variant="h6" fontWeight={800} sx={{mb:2}}>Current devices</Typography>{locations.length===0?<EmptyState text="No current locations available."/>:<Stack spacing={1}>{locations.slice(0,6).map(l=><Stack key={l.id} direction="row" justifyContent="space-between" sx={{p:1.4,borderRadius:2.5,background:'#f6fafb'}}><Typography fontWeight={700}>Device #{l.device_id}</Typography><Typography variant="body2" color="text.secondary">{Number(l.latitude).toFixed(5)}, {Number(l.longitude).toFixed(5)}</Typography></Stack>)}</Stack>}</CardContent></Card></Grid></Grid></>
}
