import { useEffect, useState } from 'react'
import { Alert, Button, Card, CardContent, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Grid, Stack, Switch, TextField, Typography } from '@mui/material'
import AddRoundedIcon from '@mui/icons-material/AddRounded'; import RefreshRoundedIcon from '@mui/icons-material/RefreshRounded'
import { devicesApi } from '../api/devices'; import { apiError } from '../api/client'; import { useAuth } from '../hooks/useAuth'; import type { Device } from '../types/api'; import PageHeader from '../components/PageHeader'; import EmptyState from '../components/EmptyState'; import Loading from '../components/Loading'
export default function DevicesPage(){const {user}=useAuth();const[rows,setRows]=useState<Device[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[open,setOpen]=useState(false);const[edit,setEdit]=useState<Device|null>(null);const[id,setId]=useState('');const[name,setName]=useState('');const[busy,setBusy]=useState(false)
const load=async()=>{setLoading(true);try{setRows(await devicesApi.list())}catch(e){setError(apiError(e))}finally{setLoading(false)}};useEffect(()=>{load()},[])
const save=async()=>{setBusy(true);setError('');try{if(edit)await devicesApi.update(edit.id,{name,is_active:edit.is_active});else await devicesApi.create({device_identifier:id,name});setOpen(false);setEdit(null);setId('');setName('');await load()}catch(e){setError(apiError(e))}finally{setBusy(false)}}
const toggle=async(d:Device)=>{try{await devicesApi.update(d.id,{is_active:!d.is_active});await load()}catch(e){setError(apiError(e))}}
if(loading)return <Loading/>;return <><PageHeader title="Devices" subtitle="Registered devices and their live tracking status." action={<Stack direction="row" spacing={1}><Button startIcon={<RefreshRoundedIcon/>} onClick={load}>Refresh</Button><Button variant="contained" startIcon={<AddRoundedIcon/>} onClick={()=>{setEdit(null);setOpen(true)}}>Add device</Button></Stack>}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Grid container spacing={2}>{rows.length===0?<Grid size={{xs:12}}><EmptyState text="No devices found."/></Grid>:rows.map(d=><Grid size={{xs:12,sm:6,lg:4}} key={d.id}><Card><CardContent><Stack spacing={1.5}><Stack direction="row" justifyContent="space-between"><Chip label={d.is_active?'Active':'Inactive'} color={d.is_active?'success':'default'} size="small"/><Typography variant="caption">#{d.id}</Typography></Stack><Typography variant="h6" fontWeight={800}>{d.name}</Typography><Typography color="text.secondary">{d.device_identifier}</Typography><Typography variant="body2">Owner user #{d.user_id}</Typography><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="body2">Tracking enabled</Typography><Switch checked={d.is_active} onChange={()=>toggle(d)} /></Stack><Button fullWidth onClick={()=>{setEdit(d);setName(d.name);setOpen(true)}}>Edit device</Button></Stack></CardContent></Card></Grid>)}</Grid><Dialog open={open} onClose={()=>!busy&&setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>{edit?'Edit device':'Add device'}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}>{!edit&&<TextField label="Device identifier" value={id} onChange={e=>setId(e.target.value)} fullWidth/>}<TextField label="Device name" value={name} onChange={e=>setName(e.target.value)} fullWidth/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancel</Button><Button variant="contained" onClick={save} disabled={busy||!name||(!edit&&!id)}>{busy?'Saving...':'Save'}</Button></DialogActions></Dialog></>}
