import { useEffect, useMemo, useState } from 'react'
import { Alert, Button, Card, CardContent, Stack, Typography } from '@mui/material'
import RefreshRoundedIcon from '@mui/icons-material/RefreshRounded'
import { Circle, CircleMarker, MapContainer, Polygon, Popup, TileLayer, useMap } from 'react-leaflet'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import { geofencesApi } from '../api/geofences'; import { locationsApi } from '../api/locations'; import { apiError } from '../api/client'; import type { Geofence, LocationEvent } from '../types/api'; import PageHeader from '../components/PageHeader'; import Loading from '../components/Loading'
function FitBounds({ geofences, locations }:{geofences:Geofence[];locations:LocationEvent[]}){const map=useMap();useEffect(()=>{const pts:[number,number][]=[];geofences.forEach(g=>{if(g.geofence_type==='circle'&&g.center_latitude!=null&&g.center_longitude!=null)pts.push([Number(g.center_latitude),Number(g.center_longitude)]);g.points.forEach(p=>pts.push([Number(p.latitude),Number(p.longitude)]))});locations.forEach(l=>pts.push([Number(l.latitude),Number(l.longitude)]));if(pts.length)map.fitBounds(L.latLngBounds(pts),{padding:[30,30],maxZoom:16})},[geofences,locations,map]);return null}
export default function MapPage(){const[geofences,setGeofences]=useState<Geofence[]>([]);const[locations,setLocations]=useState<LocationEvent[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const load=async()=>{setLoading(true);try{const[g,l]=await Promise.all([geofencesApi.list(),locationsApi.current()]);setGeofences(g);setLocations(l)}catch(e){setError(apiError(e))}finally{setLoading(false)}};useEffect(()=>{load()},[]);const center=useMemo<[number,number]>(()=>locations[0]?[Number(locations[0].latitude),Number(locations[0].longitude)]:[13.0827,80.2707],[locations]);if(loading)return <Loading text="Loading map data..."/>;return <><PageHeader title="Live Map" subtitle="Backend geofences and current device locations." action={<Button startIcon={<RefreshRoundedIcon/>} onClick={load}>Refresh</Button>}/>{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Card sx={{overflow:'hidden'}}><CardContent sx={{p:0}}><MapContainer center={center} zoom={13} style={{height:'68vh',minHeight:480,width:'100%'}}><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><FitBounds geofences={geofences} locations={locations}/>{geofences.filter(g=>g.is_active).map(g=>g.geofence_type==='circle'&&g.center_latitude!=null&&g.center_longitude!=null?<Circle key={g.id} center={[Number(g.center_latitude),Number(g.center_longitude)]} radius={Number(g.radius_meters||0)} pathOptions={{color:'#a98ac7',fillColor:'#d8c7e8',fillOpacity:.25}}><Popup><Typography fontWeight={800}>{g.name}</Typography><Typography variant="body2">Circle · {g.radius_meters} m</Typography></Popup></Circle>:<Polygon key={g.id} positions={g.points.map(p=>[Number(p.latitude),Number(p.longitude)] as [number,number])} pathOptions={{color:'#86a9bd',fillColor:'#c8e0eb',fillOpacity:.3}}><Popup><Typography fontWeight={800}>{g.name}</Typography><Typography variant="body2">Polygon · {g.points.length} points</Typography></Popup></Polygon>)}{locations.map(l=><CircleMarker key={l.id} center={[Number(l.latitude),Number(l.longitude)]} radius={8} pathOptions={{color:'#8ab6a1',fillColor:'#bfe0cb',fillOpacity:.9}}><Popup><Typography fontWeight={800}>Device #{l.device_id}</Typography><Typography variant="body2">{Number(l.latitude).toFixed(6)}, {Number(l.longitude).toFixed(6)}</Typography><Typography variant="caption">{new Date(l.recorded_at).toLocaleString()}</Typography></Popup></CircleMarker>)}</MapContainer></CardContent></Card><Stack direction="row" spacing={2} sx={{mt:2}}><Card sx={{background:'#f3eafa'}}><CardContent><Typography variant="caption">Geofences</Typography><Typography variant="h6" fontWeight={800}>{geofences.filter(g=>g.is_active).length}</Typography></CardContent></Card><Card sx={{background:'#edf7f0'}}><CardContent><Typography variant="caption">Current locations</Typography><Typography variant="h6" fontWeight={800}>{locations.length}</Typography></CardContent></Card></Stack></>}
